version: '3'
services:
  flask-app:
    build:
      context: ./backend  # Replace with the path to your Flask app directory
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - db
      - minio

  react-app:
    build:
      context: ./frontend  # Replace with the path to your React app directory
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - flask-app

  db:
    image: postgres:13  # Use the PostgreSQL Docker image
    ports:
      - "5432:5432"
    networks:
      - my-network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_API_CORS_ALLOW_ORIGIN='*'
    ports:
      - "9000:9000"
      - "9002:9002"
    networks:
      - my-network
    command: server --console-address ":9002" /data

networks:
  my-network:
