version: '3'
services:
  flask-app:
    build:
      context: ./backend  # Replace with the path to your Flask app directory
    ports:
      - "5000:5000"
    networks:
      - my-network
    environment:
      - DEBUG=True
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:pass@db:5432/db
      - SECRET_KEY=abc
      - SESSION_TYPE:=ilesystem
      - MINIO=http://minio-app:9000

    depends_on:
      - db
      - minio-app

  react-app:
    build:
      context: ./frontend  # Replace with the path to your React app directory
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - flask-app
      - minio-app
    environment:
      - VITE_BASE_URL=http://flask-app:5000
      - MINIO_BASE_URL=http://minio-app:9000

  db:
    image: postgres:13  # Use the PostgreSQL Docker image
    ports:
      - "5432:5432"
    networks:
      - my-network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  minio-app:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9002:9002"
    networks:
      - my-network
    command: server --console-address ":9002" /data

networks:
  my-network:
